[package]
name = "nativeshell_derive"
version = "0.1.1"

[lib]
proc-macro = true

edition = "2021"

[dependencies]
syn = { version = "1.0" }
quote = { version = "1.0" }
proc-macro2 = { version = "1.0" }
proc-macro-error = { version = "1.0", default-features = false }
